name: Build and deploy Release

on:
  push:
    tags:
      - v*
env:
  IMAGE_NAME: icecast2

jobs:

  push:

    name: Push image to packages
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

      - uses: actions/checkout@v2

      - name: Build image
        run: | 
          #  setting application version
          BUILD_COMMIT=$(git rev-parse --short HEAD)
          BUILD_VERSION=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
          docker build . --file Dockerfile --build-arg APP_VERSION=$BUILD_VERSION-$BUILD_COMMIT --tag $IMAGE_NAME
      - name: Log into GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          # setting image id
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          
          # getting the correct version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=$(echo $VERSION | sed -e 's/^v//')
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION