name: Release lastest image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: icecast2

jobs:

  push:

    name: Push image to packages
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag $IMAGE_NAME docker.pkg.github.com/$IMAGE_NAME:latest
          docker push docker.pkg.github.com/$IMAGE_NAME:latest